# Generated by Django 5.1.4 on 2025-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='custom_fields',
            new_name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
