# Generated by Django 5.1.2 on 2025-01-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_bulkaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together=set(),
        ),
    ]
