# Generated by Django 5.1.2 on 2025-01-24 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_email_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='unique_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('user', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('user', 'phone_number')},
        ),
    ]
