# Generated by Django 5.1.2 on 2025-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_customfield_unique_key_alter_email_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='unique_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
