# Generated by Django 5.1.2 on 2025-02-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_phonecall_contact_alter_phonecall_campaign'),
        ('contact', '0010_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='agent.agent'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('recurring', 'Recurring'), ('one_time', 'One-time')], default='one_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('paushed', 'Paushed')], default='draft', max_length=20),
        ),
    ]
