# Generated by Django 5.1.2 on 2025-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_campaign_agent_campaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('started', 'Started'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('paushed', 'Paushed')], default='draft', max_length=20),
        ),
    ]
