# Generated by Django 5.1.2 on 2025-02-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_alter_campaign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
