# Generated by Django 5.1.2 on 2025-05-22 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_campaign_twilio_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at_utc',
            field=models.DateTimeField(blank=True, help_text='Stored in UTC', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(blank=True, help_text="Timezone name, e.g., 'Asia/Kolkata'", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="User's local time", null=True),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['contact', 'is_primary'], name='contact_pho_contact_129d2c_idx'),
        ),
    ]
