# Generated by Django 5.1.2 on 2025-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_twiliophonenumber'),
        ('contact', '0015_campaign_scheduled_at_utc_campaign_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='agent',
        ),
        migrations.AddField(
            model_name='campaign',
            name='agents',
            field=models.ManyToManyField(related_name='campaigns', to='agent.agent'),
        ),
    ]
