# Generated by Django 5.1.2 on 2025-07-21 15:51

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_remove_campaign_agent_campaign_agents'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
