# Generated by Django 5.1.2 on 2025-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_phonecall_contact_alter_phonecall_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='voice',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
