# Generated by Django 5.1.2 on 2025-03-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agent_agent_id_alter_agent_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
