# Generated by Django 5.1.2 on 2024-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_user_alter_agent_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedetail',
            old_name='auth_token',
            new_name='twilio_phone',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
