# Generated by Django 5.1.2 on 2025-03-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_googlecalendarevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
