# Generated by Django 5.1.2 on 2025-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_googlecalendarevent_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='attendees',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='calendar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
