# Generated by Django 5.1.2 on 2025-04-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_googlecalendarevent_attendees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agent.phonecall')),
            ],
        ),
    ]
