# Generated by Django 5.1.2 on 2025-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='transcript',
        ),
        migrations.AddField(
            model_name='conversation',
            name='transcript_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='transcript_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
