# Generated by Django 5.1.2 on 2024-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_phonecall_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='real_agent_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
