# Generated by Django 5.1.2 on 2024-11-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_phonecall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='hand_off_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
