# Generated by Django 5.1.2 on 2024-11-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_phonecall_hand_off_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='call_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='called',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='caller',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='direction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='from_call_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_calls', to='agent.phonecall'),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='from_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='from_country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='recording_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='recording_sid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='recording_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='to_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phonecall',
            name='to_country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
