# Generated by Django 5.1.2 on 2024-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_phonecall_call_duration_phonecall_called_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='transcription_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
