# Generated by Django 5.1.2 on 2024-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_googlecalendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
