# Generated by Django 5.1.2 on 2024-12-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_agent_agent_id_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecall',
            name='agnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_calls', to='agent.agent'),
        ),
    ]
