# Generated by Django 5.1.3 on 2024-12-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_contact_contactemail_contactphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactphone',
            name='contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_calls',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_emails',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='allow_text_messages',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dnd_inbound',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='contact',
            name='dnd_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ContactEmail',
        ),
        migrations.DeleteModel(
            name='ContactPhone',
        ),
    ]
