# Generated by Django 5.1.2 on 2025-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
