# Generated by Django 5.1.2 on 2024-12-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_subaccount_address_subaccount_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='custom_data',
        ),
        migrations.AddField(
            model_name='configuration',
            name='user_limit',
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
